services:
  - type: web
    name: gmail-multi-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: GOOGLE_CLIENT_ID
        value: your_google_client_id_here
      - key: GOOGLE_CLIENT_SECRET
        value: your_google_client_secret_here
      - key: GOOGLE_REDIRECT_URI
        value: https://your-app-name.onrender.com/oauth2callback
    healthCheckPath: /
